### ISSUE TITLE
Change "importsOrder" to "imports_order"

### ISSUE THREAD

**Issue by rafal-strzelbicki** [landingi/php-coding-standards#7]
https://github.com/landingi/php-coding-standards/blob/1a42704d1c5e21a0165fd46e9f66db20b48978f3/ecs.php#L22

`importsOrder` option is not handled by Symfony and it leads to following fatal error:
```
PHP Fatal error:  Uncaught Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The option "importsOrder" does not exist. Defined options are: "imports_order", "sort_algorithm". in /home/travis/build/landingi/aws-bundle/vendor/symfony/options-resolver/OptionsResolver.php:885
Stack trace:
#0 /home/travis/build/landingi/aws-bundle/vendor/friendsofphp/php-cs-fixer/src/FixerConfiguration/FixerConfigurationResolver.php(110): Symfony\Component\OptionsResolver\OptionsResolver->resolve(Array)
#1 /home/travis/build/landingi/aws-bundle/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php(141): PhpCsFixer\FixerConfiguration\FixerConfigurationResolver->resolve(Array)
#2 /tmp/easy_coding_standard_kernel/ContainerPRMDOXY/getFixerFileProcessorService.php(26): PhpCsFixer\AbstractFixer->configure(Array)
#3 /tmp/easy_coding_standard_kernel/ContainerPRMDOXY/Symplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd42280Container.php(203): ContainerPRMDOXY\getFixerFileProcessorService::do(Object(ContainerPRMDOXY\Sympl in /home/travis/build/landingi/aws-bundle/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php on line 155
Fatal error: Uncaught Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The option "importsOrder" does not exist. Defined options are: "imports_order", "sort_algorithm". in /home/travis/build/landingi/aws-bundle/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php on line 155
PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException: [ordered_imports] Invalid configuration: The option "importsOrder" does not exist. Defined options are: "imports_order", "sort_algorithm". in /home/travis/build/landingi/aws-bundle/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php on line 155
```

**Comment by SBielawski** [comment]
@rafal-strzelbicki w jakim projekcie?

**Comment by rafal-strzelbicki** [comment]
> @rafal-strzelbicki w jakim projekcie?

@SBielawski https://github.com/landingi/aws-bundle/pull/22
